"""add scenes, shots, generation_jobs

Revision ID: ecf94eabb8c5
Revises: 75cb4350d6b8
Create Date: 2026-09-01 21:17:53.705620

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ecf94eabb8c5'
down_revision: str | Sequence[str] | None = '75cb4350d6b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column(
        'job_type', sa.Enum('INITIAL_GENERATION', 'ITERATION', name='jobtype'), nullable=False
    ),
    sa.Column(
        'status',
        sa.Enum('QUEUED', 'RUNNING', 'COMPLETE', 'FAILED_NEEDS_REVIEW', name='jobstatus'),
        nullable=False,
    ),
    sa.Column('deployed_app_url', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_generation_jobs_project_id_status',
        'generation_jobs',
        ['project_id', 'status'],
        unique=False,
    )
    op.create_table('scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=False),
    sa.Column('time_of_day', sa.String(length=50), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_script_id'), 'scenes', ['script_id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('characters', sa.JSON(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('time_of_day', sa.String(length=50), nullable=False),
    sa.Column('action_summary', sa.Text(), nullable=False),
    sa.Column('suggested_camera', sa.String(length=255), nullable=False),
    sa.Column('dialogue_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_scene_id'), 'shots', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shots_scene_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_scenes_script_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index('ix_generation_jobs_project_id_status', table_name='generation_jobs')
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
